name: Auto Format Code

on:
  # Manual trigger
  workflow_dispatch:
  # Trigger on pull requests
  pull_request:
    types: [opened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use a token that can push back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier formatting
        run: npm run format

      - name: Run ESLint auto-fix
        run: npm run lint:fix

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatted code
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "style: auto-format code with Prettier and ESLint

          - Applied Prettier formatting
          - Fixed ESLint auto-fixable issues
          - Automated code style improvements"

      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Comment on PR
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎨 **Auto-formatting applied!**\n\nYour code has been automatically formatted with Prettier and ESLint fixes have been applied. Please pull the latest changes before continuing development.\n\n```bash\ngit pull origin ${{ github.head_ref }}\n```'
            })

      - name: Success message
        if: steps.verify-changed-files.outputs.changed == 'false'
        run: echo "✅ Code is already properly formatted!"
