name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x


    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Check Prettier formatting
      run: npm run format:check

    - name: Check for unused dependencies
      run: npx depcheck

    - name: Check package vulnerabilities
      run: npm audit --audit-level high

    - name: Validate package.json
      run: npx validate-package-name

  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x


    - name: Install dependencies
      run: npm ci

    - name: Check for potential issues
      run: |
        echo "Running additional code quality checks..."
        # Check for TODO/FIXME comments
        grep -r "TODO\|FIXME\|XXX\|HACK" --include="*.js" . || echo "No TODO/FIXME found"
        
        # Check for console.log statements (should use logger)
        grep -r "console\." --include="*.js" --exclude-dir=node_modules --exclude-dir=tests . || echo "No console statements found"
