name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Create test environment file
        run: |
          cat > .env << EOF
          NODE_ENV=test
          PORT=3001
          MONGODB_URI=mongodb://localhost:27017/test_db
          JWT_SECRET=test-jwt-secret-key-for-testing-purposes-only-very-long-and-secure
          JWT_REFRESH_SECRET=test-jwt-refresh-secret-key-for-testing-purposes-only-very-long-and-secure
          JWT_EXPIRES_IN=15m
          JWT_REFRESH_EXPIRES_IN=7d
          SESSION_SECRET=test-session-secret-key-for-testing-purposes-only-very-long-and-secure
          SESSION_EXPIRES_IN=30d
          BCRYPT_SALT_ROUNDS=10
          RATE_LIMIT_WINDOW_MS=900000
          RATE_LIMIT_MAX_REQUESTS=100
          COOKIE_SECRET=test-cookie-secret-for-testing-purposes-only-very-long-and-secure
          EOF

      - name: Run ESLint
        run: npm run lint

      - name: Auto-format code with Prettier
        run: npm run format

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Check for unused dependencies
        run: npx depcheck

      - name: Check package vulnerabilities
        run: npm audit --audit-level high

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Check for potential issues
        run: |
          echo "Running additional code quality checks..."
          # Check for TODO/FIXME comments
          grep -r "TODO\|FIXME\|XXX\|HACK" --include="*.js" . || echo "No TODO/FIXME found"

          # Check for console.log statements (should use logger)
          grep -r "console\." --include="*.js" --exclude-dir=node_modules --exclude-dir=tests . || echo "No console statements found"
